openapi: 3.0.1
info:
  title: Entry Openapi Yaml
  version: 1.0.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: listenPort
paths:
  /fizzbuzz:
    get:
      operationId: operation_get_/fizzbuzz
      parameters:
      - name: amount
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
components: {}
