version: "3"

services:
  recommender:
    container_name: recommender
    image: recommender-backend:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - PORT=8080
    restart: always
    
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=scad
      - MARIADB_DATABASE=scad
      - MARIADB_USER=scad
      - MARIADB_PASSWORD=scad

  frontend:
    container_name: frontend
    image: form-frontend:latest
    depends_on:
      - db
    ports:
      - 8081:8080
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - PORT=8080
    
