version: '3'

services:
  frontend:
    container_name: frontend
    image: carl503/fizzfrontend
    ports:
     - 9090:9090
    restart: always
    environment:
      - PORT=9090
      - HOST=fizzBuzzGenerator
    depends_on:
      - fizzBuzzGenerator
      
  fizzBuzzGenerator:
    container_name: fizzbuzzgen
    image: carl503/fizzgenerator
    restart: always
    depends_on:
      - fizzBuzzCounter
    environment:
      - PORT=80
      - HOST=fizzBuzzCounter

  fizzBuzzCounter:
    container_name: counter
    image: carl503/fizzcounter
    restart: always
    environment:
      - PORT=80